"""Report commands for generating reports."""

from datetime import datetime
from pathlib import Path
from typing import Optional

import typer

from src.cli.formatters import (
    console,
    print_header,
    print_success,
    print_error,
    print_warning,
    print_info,
)

app = typer.Typer(help="Generate reports")


@app.command()
def standup(
    sprint_id: Optional[int] = typer.Option(None, "--sprint", "-s", help="Sprint ID"),
    output: Optional[str] = typer.Option(None, "--output", "-o", help="Output file"),
    format: str = typer.Option("text", "--format", "-f", help="Output format (text, markdown, json)"),
):
    """
    Generate daily standup summary.

    Includes progress, blockers, and focus areas.
    """
    from src.data.schema import get_connection
    from src.features.sprint_features import SprintFeatureExtractor
    from src.intelligence.orchestrator import JiraIntelligence

    print_header("Standup Summary")

    try:
        conn = get_connection()

        # Get sprint
        if sprint_id:
            sprint = conn.execute(
                "SELECT * FROM sprints WHERE sprint_id = ?", [sprint_id]
            ).fetchone()
        else:
            sprint = conn.execute("""
                SELECT * FROM sprints
                WHERE state = 'active'
                ORDER BY start_date DESC
                LIMIT 1
            """).fetchone()

        if not sprint:
            print_warning("No active sprint found")
            raise typer.Exit(1)

        # Get sprint features
        extractor = SprintFeatureExtractor(conn)
        features = extractor.extract_features(sprint[0])

        # Get tickets
        tickets = conn.execute("""
            SELECT key, summary, status, is_blocked
            FROM issues
            WHERE sprint_id = ?
        """, [sprint[0]]).fetchall()

        ticket_dicts = [
            {"key": t[0], "summary": t[1], "status": t[2], "is_blocked": t[3]}
            for t in tickets
        ]

        # Generate AI summary
        intel = JiraIntelligence()
        summary = intel.generate_standup_summary(features, ticket_dicts)

        if format == "json":
            import json
            result = {
                "sprint": features.get("sprint_name"),
                "date": datetime.now().isoformat(),
                "summary": summary,
                "metrics": {
                    "completion_rate": features.get("completion_rate", 0),
                    "days_remaining": features.get("days_remaining", 0),
                    "blocked_count": len([t for t in ticket_dicts if t.get("is_blocked")]),
                }
            }
            output_text = json.dumps(result, indent=2)
        elif format == "markdown":
            output_text = f"""# Standup Summary - {datetime.now().strftime('%Y-%m-%d')}

## Sprint: {features.get('sprint_name', 'Unknown')}

{summary}

---
*Generated by Jira AI Co-pilot*
"""
        else:
            output_text = summary

        if output:
            Path(output).write_text(output_text)
            print_success(f"Report saved to {output}")
        else:
            console.print()
            console.print(output_text)

    except Exception as e:
        print_error(f"Standup report failed: {e}")
        raise typer.Exit(1)


@app.command()
def sprint_health(
    sprint_id: Optional[int] = typer.Option(None, "--sprint", "-s", help="Sprint ID"),
    output: Optional[str] = typer.Option(None, "--output", "-o", help="Output file"),
    format: str = typer.Option("markdown", "--format", "-f", help="Format (markdown, html, pdf)"),
):
    """
    Generate comprehensive sprint health report.

    Includes metrics, risks, and recommendations.
    """
    from src.data.schema import get_connection
    from src.features.sprint_features import SprintFeatureExtractor
    from src.models.predictor import UnifiedPredictor
    from src.intelligence.orchestrator import JiraIntelligence

    print_header("Sprint Health Report")

    try:
        conn = get_connection()

        # Get sprint
        if sprint_id:
            sprint = conn.execute(
                "SELECT * FROM sprints WHERE sprint_id = ?", [sprint_id]
            ).fetchone()
        else:
            sprint = conn.execute("""
                SELECT * FROM sprints
                WHERE state = 'active'
                ORDER BY start_date DESC
                LIMIT 1
            """).fetchone()

        if not sprint:
            print_warning("No active sprint found")
            raise typer.Exit(1)

        print_info(f"Generating report for: {sprint[1]}")

        # Get data
        extractor = SprintFeatureExtractor(conn)
        features = extractor.extract_features(sprint[0])

        predictor = UnifiedPredictor(model_dir="models")
        risk_score = predictor.predict_sprint_risk(features)

        intel = JiraIntelligence()
        explanation = intel.explain_sprint_risk(features, risk_score)

        # Get issues
        issues = conn.execute("""
            SELECT key, summary, status, priority, story_points, assignee, is_blocked
            FROM issues WHERE sprint_id = ?
        """, [sprint[0]]).fetchall()

        # Generate report
        report_date = datetime.now().strftime('%Y-%m-%d')

        report_content = f"""# Sprint Health Report

**Sprint:** {features.get('sprint_name', 'Unknown')}
**Generated:** {report_date}
**Report By:** Jira AI Co-pilot

---

## Executive Summary

{explanation.risk_summary}

## Key Metrics

| Metric | Value |
|--------|-------|
| Progress | {features.get('progress_percent', 0):.0f}% |
| Completion Rate | {features.get('completion_rate', 0):.0f}% |
| Days Remaining | {features.get('days_remaining', 0)} |
| Total Points | {features.get('total_points', 0)} |
| Completed Points | {features.get('completed_points', 0)} |
| Risk Score | {risk_score.get('score', 0):.0f}/100 ({risk_score.get('level', 'unknown').upper()}) |

## Risk Analysis

### Main Concerns

"""
        for concern in explanation.main_concerns:
            report_content += f"- {concern}\n"

        report_content += """
### Root Causes

"""
        for cause in explanation.root_causes:
            report_content += f"- {cause}\n"

        report_content += """
## Recommendations

"""
        for i, action in enumerate(explanation.recommended_actions, 1):
            priority = action.get("priority", "medium")
            priority_marker = {"high": "🔴", "medium": "🟡", "low": "🟢"}.get(priority, "⚪")
            report_content += f"{i}. {priority_marker} **{action.get('action', '')}**\n"
            report_content += f"   {action.get('rationale', '')}\n\n"

        report_content += f"""
## Issue Summary

| Status | Count |
|--------|-------|
| Done | {len([i for i in issues if i[2] in ('Done', 'Closed')])} |
| In Progress | {len([i for i in issues if i[2] == 'In Progress'])} |
| To Do | {len([i for i in issues if i[2] in ('To Do', 'Open')])} |
| Blocked | {len([i for i in issues if i[6]])} |

## Outlook

{explanation.outlook}

---

*This report was automatically generated by Jira AI Co-pilot using ML predictions and AI analysis.*
"""

        # Handle output format
        if format == "html":
            try:
                import markdown
                html_content = f"""<!DOCTYPE html>
<html>
<head>
    <title>Sprint Health Report - {features.get('sprint_name', 'Unknown')}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }}
        table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
        th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
        th {{ background-color: #f5f5f5; }}
        h1, h2, h3 {{ color: #333; }}
        hr {{ border: none; border-top: 1px solid #eee; margin: 30px 0; }}
    </style>
</head>
<body>
{markdown.markdown(report_content, extensions=['tables'])}
</body>
</html>"""
                report_content = html_content
            except ImportError:
                print_warning("markdown package not installed, using plain text")

        elif format == "pdf":
            print_warning("PDF export requires additional dependencies")
            print_info("Install with: pip install weasyprint")
            format = "markdown"

        # Save or print
        if output:
            Path(output).write_text(report_content)
            print_success(f"Report saved to {output}")
        else:
            console.print()
            if format == "html":
                print_info("HTML output (use --output to save):")
            console.print(report_content)

    except Exception as e:
        print_error(f"Sprint health report failed: {e}")
        raise typer.Exit(1)


@app.command()
def workload(
    project: Optional[str] = typer.Option(None, "--project", "-p", help="Project key"),
    output: Optional[str] = typer.Option(None, "--output", "-o", help="Output file"),
    format: str = typer.Option("markdown", "--format", "-f", help="Format (markdown, csv, excel)"),
):
    """
    Generate developer workload report.

    Shows team distribution and recommendations.
    """
    from src.data.schema import get_connection
    from src.features.developer_features import DeveloperFeatureExtractor
    from src.models.predictor import UnifiedPredictor
    from config.settings import get_settings

    print_header("Workload Report")

    settings = get_settings()
    project_key = project or settings.jira.project_key

    try:
        conn = get_connection()
        extractor = DeveloperFeatureExtractor(conn)
        predictor = UnifiedPredictor(model_dir="models")

        # Get developers
        developers = extractor.get_active_developers(project_key)

        if not developers:
            print_warning("No active developers found")
            return

        # Collect data
        data = []
        for dev_id in developers:
            features = extractor.extract_features(dev_id, project_key)
            workload = predictor.assess_developer_workload(features)

            data.append({
                "developer": features.get("pseudonym", f"dev_{dev_id[:8]}"),
                "wip_count": features.get("wip_count", 0),
                "wip_points": features.get("wip_points", 0),
                "blocked_count": features.get("blocked_count", 0),
                "completed_7d": features.get("completed_last_7_days", 0),
                "status": workload.get("status", "optimal"),
                "score": workload.get("score", 0),
            })

        # Sort by status severity
        status_order = {"overloaded": 0, "high": 1, "optimal": 2, "underloaded": 3}
        data.sort(key=lambda x: status_order.get(x["status"], 2))

        if format == "csv":
            import csv
            from io import StringIO

            output_io = StringIO()
            writer = csv.DictWriter(output_io, fieldnames=data[0].keys())
            writer.writeheader()
            writer.writerows(data)
            report_content = output_io.getvalue()

        elif format == "excel":
            try:
                import pandas as pd
                df = pd.DataFrame(data)

                if output:
                    df.to_excel(output, index=False)
                    print_success(f"Report saved to {output}")
                    return
                else:
                    print_warning("Excel format requires --output file")
                    format = "markdown"
            except ImportError:
                print_warning("pandas/openpyxl not installed, using markdown")
                format = "markdown"

        if format == "markdown" or format != "csv":
            report_content = f"""# Developer Workload Report

**Project:** {project_key}
**Generated:** {datetime.now().strftime('%Y-%m-%d')}

## Team Overview

| Developer | WIP | Points | Blocked | 7-day Velocity | Status |
|-----------|-----|--------|---------|----------------|--------|
"""
            for d in data:
                status_icon = {
                    "overloaded": "🔴",
                    "high": "🟡",
                    "optimal": "🟢",
                    "underloaded": "⚪"
                }.get(d["status"], "⚪")

                report_content += f"| {d['developer']} | {d['wip_count']} | {d['wip_points']} | {d['blocked_count']} | {d['completed_7d']} | {status_icon} {d['status']} |\n"

            # Summary
            overloaded = [d for d in data if d["status"] == "overloaded"]
            underloaded = [d for d in data if d["status"] == "underloaded"]

            report_content += f"""
## Summary

- **Total Team Members:** {len(data)}
- **Overloaded:** {len(overloaded)}
- **Underloaded:** {len(underloaded)}

"""
            if overloaded:
                report_content += "### Action Required\n\n"
                for d in overloaded:
                    report_content += f"- **{d['developer']}** has {d['wip_points']} points in progress - consider redistributing work\n"

            report_content += "\n---\n*Generated by Jira AI Co-pilot*\n"

        # Output
        if output:
            Path(output).write_text(report_content)
            print_success(f"Report saved to {output}")
        else:
            console.print()
            console.print(report_content)

    except Exception as e:
        print_error(f"Workload report failed: {e}")
        raise typer.Exit(1)


@app.command()
def export(
    report_type: str = typer.Argument(..., help="Report type (sprint, workload, velocity)"),
    output: str = typer.Option(..., "--output", "-o", help="Output file path"),
    format: str = typer.Option("pdf", "--format", "-f", help="Format (pdf, excel, html)"),
    sprint_id: Optional[int] = typer.Option(None, "--sprint", "-s", help="Sprint ID"),
    project: Optional[str] = typer.Option(None, "--project", "-p", help="Project key"),
):
    """
    Export report to file.

    Supports PDF, Excel, and HTML formats.
    """
    print_header(f"Export {report_type.title()} Report")

    try:
        if format == "pdf":
            try:
                from weasyprint import HTML
                print_info("Generating PDF...")

                # Generate HTML first, then convert
                # This is a simplified version - full implementation would
                # call the appropriate report command and convert
                print_warning("Full PDF export requires weasyprint installation")
                print_info("Install with: pip install weasyprint")

            except ImportError:
                print_error("weasyprint not installed")
                print_info("Install with: pip install weasyprint")
                raise typer.Exit(1)

        elif format == "excel":
            try:
                import pandas as pd
                print_info("Generating Excel...")

                # Would collect data and create Excel file
                print_warning("Excel export implementation depends on report type")

            except ImportError:
                print_error("pandas/openpyxl not installed")
                print_info("Install with: pip install pandas openpyxl")
                raise typer.Exit(1)

        else:
            # Delegate to specific report command
            if report_type == "sprint":
                sprint_health(sprint_id=sprint_id, output=output, format=format)
            elif report_type == "workload":
                workload(project=project, output=output, format=format)
            else:
                print_error(f"Unknown report type: {report_type}")
                raise typer.Exit(1)

    except Exception as e:
        print_error(f"Export failed: {e}")
        raise typer.Exit(1)
